version: "3"
services:
  mssql:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports:
    - '1433:1433'